added grpc services and tests for them
OlehSarapuk/ajax-onboarding-project pull request #20
Opened 2023-09-20 08:27 UTC by OlehSarapuk

2023-09-20 21:03 UTC, ajax-gnatiuk-s requested changes

2023-09-20 21:03 UTC, ajax-gnatiuk-s commented on src/test/java/com/example/ajaxonboardingproject/NatsMovieSessionControllerTests.kt
> +        assertThat(expected.movieSession).isEqualTo(actual.movieSession)
```
assertThat(<ACTUAL>).isEqualTo(<EXPECTED>)
```

2023-09-20 21:03 UTC, ajax-gnatiuk-s commented on src/main/java/com/example/ajaxonboardingproject/nats/grpc/MovieGrpcService.kt
> +            .forEach { responseObserver.onNext(it) }
```suggestion
        movieService.getAll()
            .map { movieConverter.movieToProtoResponse(it) }
            .doOnNext { responseObserver.onNext(it) }
            .blockLast()
```

?

2023-09-20 21:03 UTC, ajax-gnatiuk-s commented on src/main/java/com/example/ajaxonboardingproject/nats/grpc/MovieGrpcService.kt
> +        responseObserver.onCompleted()
```suggestion
        movieService.add(movieConverter.protoRequestToMovie(request))
            .doOnNext { responseObserver.onNext(movieConverter.movieToProtoResponse(it)) }
            .block()
        responseObserver.onCompleted()
```

2023-09-21 07:45 UTC, ajax-gnatiuk-s approved these changes

2023-09-21 12:23 UTC, OlehSarapuk commented on src/test/java/com/example/ajaxonboardingproject/NatsMovieSessionControllerTests.kt
> +        assertThat(expected.movieSession).isEqualTo(actual.movieSession)
Done! ✅

2023-09-21 12:23 UTC, OlehSarapuk commented on src/main/java/com/example/ajaxonboardingproject/nats/grpc/MovieGrpcService.kt
> +            .forEach { responseObserver.onNext(it) }
Done! ✅

2023-09-21 12:23 UTC, OlehSarapuk commented on src/main/java/com/example/ajaxonboardingproject/nats/grpc/MovieGrpcService.kt
> +        responseObserver.onCompleted()
Done! ✅

2023-09-21 12:49 UTC, Wectro20 approved these changes

2023-09-21 15:46 UTC, merged